
project_id = "ubztjjxmldogpwawcnrj"

[functions.send-contact-form]
verify_jwt = false

[functions.password-reset-fix]
verify_jwt = false

[functions.generate-reset-link]
verify_jwt = false

[functions.set-admin-password]
verify_jwt = false
