
# This file controls the configuration for your Supabase project.
# For further information on how to set up your project, check out the Supabase docs at:
# https://supabase.com/docs

# Note: The project_id is read from the supabase_project_ref env var.
# If you want to use a different project ID, you can set it here.
project_id = "ubztjjxmldogpwawcnrj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 3600

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = 52428800

[analytics]
enabled = false

[cdn]
enabled = false

[functions]
check-user-exists = { verify_jwt = true }
